### ISSUE TITLE
Lack of project templates

### ISSUE THREAD

**Issue by BachiMjavanadze** [rsaz/csharp-snippet-productivity#12]
Can you please add more project templates? Fore example: Nunit, MStest, xUnit test projects. 

Also please add "Minimal Web API". With Visual Studio IDE you can easily create it, you just need to uncheck this:

![1](https://user-images.githubusercontent.com/38082501/168460900-f8cb220a-8bc1-4b25-82b7-b30b4514901c.jpeg)

.Net CLI command for "Minimal Web API":

`dotnet new webapi -minimal -o PROJECT_NAME`

**Comment by rsaz** [comment]
@BachiMjavanadze I added all project templates requested in the version v1.3.0. (minimal webapi, mstest, nunit, xunit)
In a soon future I will recreate the project creating webview with a more interactive interface.
