### ISSUE TITLE
Incorrect behavior when creating new solution

### ISSUE THREAD

**Issue by BachiMjavanadze** [rsaz/csharp-snippet-productivity#13]
If the solution already exists and I create new solution with the same name it doesn't warn that the folder already exists but just embeds project into existing solution. 

For example: I have the solution (folder) "Temp" with project "App1". If I create new solution (folder) with the same name ("Temp") and with new project (say "App2") the extention will not warn that "Temp" folder already exists and "App2" will be added into existing "Temp".

**Comment by rsaz** [comment]
Hi @BachiMjavanadze problem fixed in version v1.3.0. If you try to create a solution with the same name within the same path you will get an error such as the one below. 
![image](https://user-images.githubusercontent.com/4088378/177031198-c876fcef-4fc6-4763-a6d5-0bb5de4d8b86.png)

**Comment by BachiMjavanadze** [comment]
@rsaz problem almost gone :) in case of error it should not open existing project I guess
