### ISSUE TITLE
Error creating Minimal WEB API project

### ISSUE THREAD

**Issue by BachiMjavanadze** [rsaz/csharp-snippet-productivity#17]
When I try to create minimal web api project get this error:

![min-web-error](https://user-images.githubusercontent.com/38082501/178432932-b0ce70d5-9722-4a41-ba84-bdc8dc432095.PNG)

**Comment by rsaz** [comment]
Thanks for reporting this issue. I will be looking to that shortly.

**Comment by rsaz** [comment]
Hi @BachiMjavanadze 

Check the latest version of the extension, 2.0. It has a bunch of new features. It also resolves this problem you mentioned above.
There is no more minimum api template: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0

The minimum api is what is called Web ASP.NET Core Empty

![image](https://github.com/rsaz/csharp-snippet-productivity/assets/4088378/5ed95cf3-b668-4109-8f06-a660e84b4932)

This new version 2.0 allows you to select the group of applications like in visual studio, and the subgroups. There are more changes to come in the next couples weeks. Stay tuned!
