### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by danielpineda243** [rsaz/csharp-snippet-productivity#2]
- Issue Type: `Performance`
- Extension Name: `csharp-snippet-productivity`
- Extension Version: `1.2.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Fam.PinedaBarahona\AppData\Local\Temp\richardzampieriprog.csharp-snippet-productivity-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by rsaz** [comment]
@danielpineda243 I just saw your ticket. Thank you for letting me know. I will take a look into that.
Can you reproduce, send me pictures or video, or steps that you take that is cause a high cpu usage? I haven't seen any other user complain about it yet.

I appreciate your help to fix the issue

**Comment by rsaz** [comment]
All functions calls are in (ms). Layout context switch is something that I intend to look at in the future. Right now is giving to all users a great and fast experience. Let me know if you still face some loading issues.
