### ISSUE TITLE
Error Creating New React SPA Project

### ISSUE THREAD

**Issue by dnmyers** [rsaz/csharp-snippet-productivity#24]
Receiving an error when trying to create a new React SPA project.  The command to create the new project isn't including the framework to target.  This is the command it is currently executing:

dotnet new react --language c# -n TestProject -o 'e:\Coding\.NET\Projects\TestProject' --framework  --force

And the error:
"Error: Invalid option(s):
--framework --force
   '--force' is not a valid value for --framework. The possible values are:
      net5.0          - Target net5.0
      net6.0          - Target net6.0
      net7.0          - Target net7.0
      netcoreapp2.1   - Target netcoreapp2.1
      netcoreapp3.1   - Target netcoreapp3.1"

Just need to add the selected target framework after the --framework flag to fix this.

![image](https://github.com/rsaz/csharp-snippet-productivity/assets/12505165/2b40473e-a9ad-4837-99d4-de5b1b58b91d)

**Comment by rsaz** [comment]
Hi @dnmyers thank you for reporting this issue.

A new version of the extension is about come out, version 2.0. In this version you will find:

- All project templates available on dotnet new list can be created within the extension
- Performance improvements
- Snippets fix
- Support for .NET 7.0 and 8.0
- Framework compatibility validation. This is the issue you're referring here in this ticket. Currently, if you use Visual Studio Community you can install a react project and Visual Studio Community will take care the framework compatibility for you. The default behavior is too use the most up to date compatible .net version that supports the project template you're trying to use.

My implementation fix this issue but has a better approach I believe. Now you will know when a framework doesn't support the current template you're trying to create and the extension will tell you what version you can use. Right now this is a configuration and it is tested for most of the templates. As the user start using other templates, if we have issues like this I can quickly adjust and add in the dictionary the appropriate compatible .net version.

Here is a sneak peek of this issue being resolved.

![image](https://github.com/rsaz/csharp-snippet-productivity/assets/4088378/9e6275fb-e876-40f3-8915-5286218f183c)

Stay tuned for the v2.0!
