### ISSUE TITLE
Folders with spaces do not work

### ISSUE THREAD

**Issue by mikael-bergstrom-ntisthlm** [rsaz/csharp-snippet-productivity#4]
When creating a new solution/project, spaces anywhere in the path will result in error, as spaces are not escaped when the dotnet new etc commands are run.

**Comment by rsaz** [comment]
> > When creating a new solution/project, spaces anywhere in the path will result in error, as spaces are not escaped when the dotnet new etc commands are run.
> 
> Hi @mikael-bergstrom-ntisthlm **I am on it**. Thanks for reporting that. I will fix as soon as I can and release it in the new incoming version with new features.

Problem solved. Now you can create solutions/projects using folders with empty space. The solution is in the version1.2.6. Thank you again for raising the issue.

Regards
