### ISSUE TITLE
Feature request – Remembering last Location

### ISSUE THREAD

**Issue by mikael-bergstrom-ntisthlm** [rsaz/csharp-snippet-productivity#5]
I'm using this extension in a classroom setting, as it provides a quick and easy way to create new projects and get up and running.

My students suggested that it would be even easier to use if the Location box in the Create Project form was pre-filled with the last used location. My guess is a lot of people keep most of their projects in the same base folder, and that would save us a lot more clicks…

Just an idea.

**Comment by rsaz** [comment]
> I'm using this extension in a classroom setting, as it provides a quick and easy way to create new projects and get up and running.
> 
> My students suggested that it would be even easier to use if the Location box in the Create Project form was pre-filled with the last used location. My guess is a lot of people keep most of their projects in the same base folder, and that would save us a lot more clicks…
> 
> Just an idea.

This is a good idea, I will be including in the next release, thank you.

**Comment by rsaz** [comment]
I've created a configuration property called **default Folder For Project Creation** in preferences, so people can set their default folder repository. This feature will be released in the version 1.2.7
