### ISSUE TITLE
Escaping from New Class creation means undefined.cs is created

### ISSUE THREAD

**Issue by mikael-bergstrom-ntisthlm** [rsaz/csharp-snippet-productivity#7]
Small bug? If you start creating a class/interface and cancel out of it using ESC key, an item named "undefined" is created.

I'm guessing intended/expected behavior would be that nothing be created, and the action be completely cancelled.

**Comment by rsaz** [comment]
> Small bug? If you start creating a class/interface and cancel out of it using ESC key, an item named "undefined" is created.
> 
> I'm guessing intended/expected behavior would be that nothing be created, and the action be completely cancelled.

That's by design, I can change that to cancel the operation if user press esc  for sure.

**Comment by rsaz** [comment]
Problem solved and it is in the release 1.2.7
