### ISSUE TITLE
Bug: Create Project button won't light up

### ISSUE THREAD

**Issue by mikael-bergstrom-ntisthlm** [rsaz/csharp-snippet-productivity#8]
In the Create Project dialog, the button won't light up unless either:

- The contents of the Solution Name text box is _changed_. Just clicking the box is not enough.
- The Solution Name text box is tabbed _into_. Clicking the box, the tabbing out is not enough.
- The Project Name text box loses focus, and is subsequently edited.

To reproduce:

- Open Create Project dialog
- Choose template
- Click the Project Name text box. Type in a name.
- Click the Location text box. The Solution Name updates, but the Create Project button does not light up.

**Comment by rsaz** [comment]
Hi @mikael-bergstrom-ntisthlm sorry for the long wait, but you can find a solution for your request in the version 1.2.9.
Now when you create the project and give it a name to your project and press tab, solution gets copy project name as visual studio and the path which is based on the configuration {"csharp-snippet-productivity.defaultFolderForProjectCreation": "C:\\your path",} is set automatically, so the button highlight just after the first tab you press.

Thank you for your patient and help on making the extension better.
